# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_University', '0005_auto_20160605_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='time_birth',
        ),
        migrations.AlterField(
            model_name='student',
            name='date_birth',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_University.Group'),
        ),
    ]
